name: jank
version: 0.0.1
synopsis: Command line JSON processor
maintainer: Benjamin Kovach <bkovach13@gmail.com>
license: MIT
github: 5outh/jank
category: Development

ghc-options: -Wall

dependencies:
  - base

library:
  source-dirs: src
  exposed-modules:
    - Jank
  other-modules:
    - Jank.Language
    - Jank.Interpret
    - Jank.Types
  dependencies:
    - lens
    - text
    - lens-aeson
    - aeson
    - optparse-applicative
    - string-conversions
    - unordered-containers
    - megaparsec
    - bytestring
    - free
    - vector

executables:
  jank:
    main: Main.hs
    source-dirs: app
    dependencies:
      - jank
